#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Abuse
version:      1.023
version_from: lib/Mail/Abuse.pm
installdirs:  site
requires:
    Text::CSV_XS:                  0
    Test::More:                    0
    Mail::Mailer:                  0
    MIME::Entity:                  0
    NetAddr::IP:                   3
    HTML::Parser:                  0
    Digest::MD5:                   0
    File::Spec:                    0
    Net::POP3:                     2.23
    DBI:                           1.48
    Date::Parse:                   0
    MIME::Parser:                  0
    Storable:                      0
    Tie::NetAddr::IP:              1.51
    Date::Manip:                   0
    File::Find:                    0
    File::Path:                    0
    WWW::Mechanize:                0
    Params::Validate:              0
    IO::File:                      0
    IO::Zlib:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
